name: engli_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_tts: ^0.6.0
  #shared_preferences: "^1.0.0"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^0.1.3
  firebase_auth: ^1.0.2
  firebase_core : ^1.0.3
  cloud_firestore: ^1.0.4
  provider: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  image_path: "images/logo.png"
  android: true
  ios: true



# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - icons/
#    - images/kids-read.jpg
#    - images/table.jpg
#    - images/chair.jpg
#    - images/bed.jpg
#    - images/cupboard.jpg
#    - images/hamster.jpg
#    - images/dog.jpg
#    - images/cat.jpg
#    - images/fish.jpg
#    - images/logo.jpg
#    - icons/pencil.jpg
#    - icons/microphone.png
#    - images/brother.jpg
#    - images/father.png
#    - images/friday.png
#    - images/meat.jpg
#    - images/monday.png
#    - images/mother.jpg
#    - images/pizza.jpg
#    - images/rice.jpg
#    - images/saturday.png
#    - images/sister.jpg
#    - images/soup.png
#    - images/sunday.png
#    - images/A.jpg
#    - images/R.jpg
#    - images/W.jpg
#    - images/F.jpg
#    - images/black.png
#    - images/blue.png
#    - images/green.jpg
#    - images/red.png
#    - images/fireworks.gif


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Abraham-h
      fonts:
        - asset: fonts/Abraham-Regular.ttf
    - family: Comix-h
      fonts:
        - asset: fonts/comixno2clm_bold-webfont.ttf
    - family: Dorian-h
      fonts:
        - asset: fonts/dorianclm-book-webfont.ttf
    - family: Gan-h
      fonts:
        - asset: fonts/ganclm_bold-webfont.ttf
    - family: Miri-h
      fonts:
        - asset: fonts/miriwin-webfont.ttf
    - family: Nehama-h
      fonts:
        - asset: fonts/nehama-webfont.ttf
    - family: Trashim-h
      fonts:
        - asset: fonts/trashimclm-bold-webfont.ttf
    - family: Yehuda-h
      fonts:
        - asset: fonts/yehudaclm-bold-webfont.ttf
    - family: FredokaOne-e
      fonts:
        - asset: fonts/FredokaOne-Regular.ttf
    - family: AkayaK-e
      fonts:
        - asset: fonts/AkayaKanadaka-Regular.ttf
    - family: AkayaT-e
      fonts:
        - asset: fonts/AkayaTelivigala-Regular.ttf
    - family: Carter-e
      fonts:
        - asset: fonts/CarterOne-Regular.ttf
    - family: Courgette-e
      fonts:
        - asset: fonts/Courgette-Regular.ttf
    - family: IndieFlower-e
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf
    - family: PottaOne-e
      fonts:
        - asset: fonts/PottaOne-Regular.ttf
    - family: RocknRoll-e
      fonts:
        - asset: fonts/RocknRollOne-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
